name: Manual Deployment of knowledge-curator.lundandco.net

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'knowledge-curator.lundandco.net'
        type: string

jobs:

  meta:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.vars.outputs.ENVIRONMENT }}
      STACK_NAME: ${{ steps.vars.outputs.STACK_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Env Vars
        id: vars
        run: |
          # Use workflow input, fallback to vars.LIVE_ENV, or use default
          if [ -n "${{ github.event.inputs.environment }}" ]; then
            ENVIRONMENT="${{ github.event.inputs.environment }}"
          elif [ -n "${{ vars.LIVE_ENV }}" ]; then
            ENVIRONMENT="${{ vars.LIVE_ENV }}"
          else
            ENVIRONMENT="knowledge-curator.lundandco.net"
          fi
          echo "ENVIRONMENT=${ENVIRONMENT}" >> $GITHUB_OUTPUT
          echo "STACK_NAME=${ENVIRONMENT//./-}" >> $GITHUB_OUTPUT

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - meta
    runs-on: ubuntu-latest
    environment: ${{ needs.meta.outputs.ENVIRONMENT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate deployment secrets
        run: |
          if [ -z "${{ secrets.DEPLOY_HOST }}" ]; then
            echo "::error::DEPLOY_HOST secret is not configured"
            exit 1
          fi
          if [ -z "${{ secrets.DEPLOY_USER }}" ]; then
            echo "::error::DEPLOY_USER secret is not configured"
            exit 1
          fi
          if [ -z "${{ secrets.DEPLOY_SSH }}" ]; then
            echo "::error::DEPLOY_SSH secret is not configured"
            exit 1
          fi

      - name: Set deployment parameters
        id: deploy-params
        run: |
          echo "remote_port=${{ secrets.DEPLOY_PORT || 22 }}" >> $GITHUB_OUTPUT
          if [ -n "${{ secrets.ENV_FILE }}" ]; then
            echo "env_file=${{ secrets.ENV_FILE }}" >> $GITHUB_OUTPUT
          else
            echo "env_file=" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to cluster
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ steps.deploy-params.outputs.remote_port }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: devops/stacks/${{ needs.meta.outputs.ENVIRONMENT }}.yml
          stack_name: ${{ needs.meta.outputs.STACK_NAME }}
          stack_param: ${{ github.ref_name }}
          env_file: ${{ steps.deploy-params.outputs.env_file }}
          deploy_timeout: 480
